module.exports = {
    ERRORS: {
        ERR_UNKNOWN_ERROR: 'ERR_UNKNOWN_ERROR',
        ERR_INVALID_IMAGE: 'ERR_INVALID_IMAGE',
        ERR_INVALID_PSM: 'ERR_INVALID_PSM',
        ERR_INVALID_OEM: 'ERR_INVALID_OEM',
        ERR_INVALID_TESSDATA_DIR: 'ERR_INVALID_TESSDATA_DIR',
        ERR_INVALID_OUTPUT_BASE: 'ERR_INVALID_OUTPUT_BASE',

        ERR_COMMAND_RUN_ERROR: 'ERR_COMMAND_RUN_ERROR',
        ERR_COMMAND_CHECK_ERROR: 'ERR_COMMAND_CHECK_ERROR',

        ERR_FILE_NO_FIND: 'ERR_FILE_NO_FIND',
        ERR_TESSERACT_NO_INSTALL: 'ERR_TESSERACT_NO_INSTALL',
    }
};